<?php
include 'conn.php';
echo "<!DOCTYPE html>\n"; 
echo "<html lang=\"en\" class=\"no-js\">\n"; 
echo "	<head>\n"; 
echo "		<meta charset=\"UTF-8\" />\n"; 
echo "		<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\"> \n"; 
echo "		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"> \n"; 
echo "		<title>Anderson D&T </title>\n"; 
echo "		<meta name=\"description\" content=\"A sidebar menu as seen on the Google Nexus 7 website\" />\n"; 
echo "		<meta name=\"keywords\" content=\"google nexus 7 menu, css transitions, sidebar, side menu, slide out menu\" />\n"; 
echo "		<meta name=\"author\" content=\"Codrops\" />\n"; 
echo "		<link rel=\"shortcut icon\" href=\"../favicon.ico\">\n"; 
echo "		<link rel=\"stylesheet\" type=\"text/css\" href=\"css/normalize.css\" />\n"; 
echo "\n"; 
echo "      	<link rel=\"stylesheet\" type=\"text/css\" href=\"css/menu.css\" />\n"; 
echo "		<script src=\"js/modernizr.custom.js\"></script>\n"; 
echo "        <style>\n"; 
echo "			#workstation {\n"; 
echo "				padding: 5px;\n"; 
echo "				margin-left: 5px;\n"; 
echo "				width: 225%;\n"; 
echo "				height: 500px;\n"; 
echo "				background-color: #7c96b1;\n"; 
echo "				float: left;\n"; 
echo "						   \n"; 
echo "				border-radius: 5px;\n"; 
echo "				-moz-border-radius:5px;\n"; 
echo "				-webkit-border-radius:5px;\n"; 
echo "			}\n"; 
echo "			#notes { \n"; 
echo "					 padding-left: 10px;\n"; 
echo "					 margin-left: 20px;\n"; 
echo "					 margin-bottom: 10px;\n"; 
echo "					 background-color: #7c96b1;\n"; 
echo "					 width: 260px;\n"; 
echo "					 float:left;\n"; 
echo "					 					 \n"; 
echo "					 border: 1px solid #c6d0da;\n"; 
echo "					 border-radius:5px;\n"; 
echo "				     -moz-border-radius:5px;\n"; 
echo "				     -webkit-border-radius:5px;\n"; 
echo "			}\n"; 
echo "			#dropdown {\n"; 
echo "	    		border: 1px solid #FFFFFF;\n"; 
echo "			    height:450px;\n"; 
echo "			    position:relative;\n"; 
echo "			    width:200%;\n"; 
echo "\n"; 
echo "			    border-radius:5px;\n"; 
echo "	    		-moz-border-radius:5px;\n"; 
echo "			    -webkit-border-radius:5px;\n"; 
echo "			}\n"; 
echo "			table { \n";
echo "				border-collapse: collapse;\n";
echo "				border-radius: 3px;\n";
echo "			}\n";
echo "			table, td, th { \n";
echo "				border: 1px solid #56ffff; \n";
echo "			}\n";
echo "			table tr:nth-child(odd) { \n";
echo "				background-color: #b3d0f2; \n";
echo "			}\n";
echo "			table tr:nth-child(even) {\n";
echo "				background-color: #e5e5e5;\n";
echo "			}\n";
echo "		</style>\n"; 
echo "	</head>\n"; 
echo "	<body>\n"; 
echo "    	<div>\n"; 
echo "        	<div style=\" padding-left: 30px; padding-top: 30px; width: 600px;\">\n"; 
echo "            \n"; 
$phase = $_GET['phase'];
$pstmt = $dbConn->prepare('SELECT * FROM `student` WHERE StudentID NOT IN (SELECT `StudentID` FROM `log` WHERE `phase` = ?)');
$pstmt->bindParam(1, $phase, PDO::PARAM_INT);
$pstmt->execute();
$pstmt->bindColumn(1, $studentID);

echo"<table style='width:100%; font-family: 'Lato', Arial, sans-serif;'>";
echo"<th>Student Name</th>";
echo"<th>Current Phase</th>";
echo"<th>Last Seen</th>";

while ($pstmt->fetch()) {
	$pstmt1 = $dbConn->prepare('SELECT * FROM `student` WHERE `StudentID` = ?');
	$pstmt1->bindParam(1, $studentID, PDO::PARAM_INT);
	$pstmt1->execute();
	$pstmt1->bindColumn(2, $studentName);
	$pstmt1->fetch();
	
	$pstmt1 = $dbConn->prepare('SELECT MAX(phase) FROM `log` WHERE `StudentID` = ?');
	$pstmt1->bindParam(1, $studentID, PDO::PARAM_INT);
	$pstmt1->execute();
	$pstmt1->bindColumn(1, $maxphase);
	$pstmt1->fetch();
	
	
	$pstmt1 = $dbConn->prepare('SELECT `Timestamp` FROM `log` WHERE `StudentID` = ? ORDER by `logID` DESC LIMIT 1');
	$pstmt1->bindParam(1, $studentID, PDO::PARAM_INT);
	$pstmt1->execute();
	$pstmt1->bindColumn(1, $lastSeen);
	$pstmt1->fetch();

	echo "<tr>";
	echo "<td>", $studentName, "</td>";
	echo "<td>", $maxphase, "</td>";
	echo "<td>", $lastSeen, "</td>";
   	echo "</tr>";
}
echo "</table>";
echo "            </div>\n"; 
echo "        </div>\n"; 
echo "<br><button style=\"margin-left: 30px; color: #566473; border-radius: 4px;\" onclick=\"goBack()\">Go Back</button>\n"; 
echo "\n"; 
echo "<script>\n"; 
echo "function goBack() {\n"; 
echo "    window.history.back()\n"; 
echo "}\n"; 
echo "</script>\n";
echo "	</body>\n"; 
echo "</html>\n";
?>